# Site settings
title: XML-Парсер Участков РосРеестра
email: me@gbezyuk.ru
description: > # this means to ignore newlines until "baseurl:"
  https://github.com/gbezyuk/rosreestr-xml documenation site.
baseurl: "/rosreestr-xml" # the subpath of your site, e.g. /blog/
url: "http://gbezyuk.github.io" # the base hostname & protocol for your site
twitter_username: shcoder
github_username:  gbezyuk

# Build settings
markdown: kramdown
kramdown:
  input: GFM
