# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to='', verbose_name='file')),
                ('original_file_name', models.CharField(max_length=100, verbose_name='original file name')),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cadastral_number', models.CharField(max_length=40, verbose_name='cadastral number')),
                ('json_representation', models.TextField(verbose_name='csv representation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.OriginalDocument', verbose_name='document')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
                'ordering': ('-modified',),
            },
        ),
    ]
