# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralblock',
            name='cadastral_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='cadastral number'),
        ),
        migrations.AlterField(
            model_name='cadastralblock',
            name='file',
            field=models.FileField(max_length=500, upload_to='uploads/cadastral_blocks', verbose_name='file'),
        ),
    ]
