# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastralblock',
            name='root_node_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='root node name'),
        ),
        migrations.AddField(
            model_name='cadastralblock',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('uploaded', 'uploaded'), ('parced', 'parced')], default='new', max_length=20, verbose_name='status'),
        ),
    ]
