# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaldocument',
            name='cadastral_number',
            field=models.CharField(default='', max_length=40, verbose_name='cadastral number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='json_representation',
            field=models.TextField(verbose_name='CSV representation'),
        ),
    ]
